"""removed superuser

Revision ID: 2d0d14c53028
Revises: 56df84e1ed61
Create Date: 2024-06-15 16:47:11.371839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0d14c53028'
down_revision: Union[str, None] = '56df84e1ed61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_user', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
